services:
  - type: web
    name: chatdb
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p $PORT core.asgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: chatdb-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: REDIS_URL
        fromService:
          name: chatdb-redis
          type: redis
          property: connectionString

  - type: redis
    name: chatdb-redis
    ipAllowList: []
    plan: free

databases:
  - name: chatdb-db
    databaseName: chatdb
    user: chatdb
    plan: free 